# Generated by Django 5.0 on 2023-12-20 11:18

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('book_name', models.CharField(max_length=150)),
                ('author', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(default=1)),
                ('subject', models.CharField(max_length=2000)),
                ('book_add_time', models.TimeField(default=datetime.datetime(2023, 12, 20, 11, 18, 17, 567763, tzinfo=datetime.timezone.utc))),
                ('book_add_date', models.DateField(default=datetime.date(2023, 12, 20))),
                ('pubulisher', models.CharField(default='', max_length=200)),
                ('book_category', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='BookManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_manager_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='IssuedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(default=datetime.date(2023, 12, 20))),
                ('return_date', models.DateField(blank=True, null=True)),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_library.book')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=50)),
                ('student_card', models.CharField(default=None, max_length=50)),
                ('student_edu', models.IntegerField(default=0)),
                ('lend_count', models.IntegerField(default=0)),
                ('isbn', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='system_library.book')),
            ],
        ),
    ]
