# Generated by Django 5.0 on 2023-12-20 11:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_library', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_add_time',
            field=models.TimeField(default=datetime.datetime(2023, 12, 20, 11, 18, 20, 191611, tzinfo=datetime.timezone.utc)),
        ),
    ]
