# Generated by Django 5.0 on 2023-12-21 09:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_library', '0003_remove_bookcategory_num_alter_book_book_add_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_add_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 21, 9, 15, 34, 44824, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='lend',
            name='lend_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 21, 9, 15, 34, 47153, tzinfo=datetime.timezone.utc)),
        ),
    ]
