# Generated by Django 5.0 on 2023-12-21 12:45

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_library', '0007_alter_book_book_add_datetime_alter_lend_lend_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='pubulisher',
            new_name='publisher',
        ),
        migrations.AlterField(
            model_name='book',
            name='book_add_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 21, 12, 45, 20, 517579, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='lend',
            name='lend_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 21, 12, 45, 20, 520429, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserve_date', models.DateTimeField(default=datetime.datetime(2023, 12, 21, 12, 45, 20, 521067, tzinfo=datetime.timezone.utc))),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_library.book')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_library.person')),
            ],
            options={
                'unique_together': {('person', 'book')},
            },
        ),
    ]
