# Generated by Django 5.0 on 2023-12-21 12:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_library', '0009_alter_book_book_add_datetime_alter_lend_lend_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_add_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 21, 12, 54, 25, 367395, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='lend',
            name='lend_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 21, 12, 54, 25, 369624, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='reserve_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 22, 12, 54, 25, 370231, tzinfo=datetime.timezone.utc)),
        ),
    ]
